import type { Metadata } from "next";
import { Assistant } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/components/application/GlobalProvider";

const AssistantFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${AssistantFont.className} antialiased`}
        >
        <GlobalProvider>
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
